-- ==============================================================================
-- Procare Console - Global System Settings & AI Model Switcher Schema
-- Table: system_settings
-- ==============================================================================

-- 1. Create table if not exists
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active_chatbot_model TEXT NOT NULL DEFAULT 'gemini' CHECK (active_chatbot_model IN ('gemini', 'groq')),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure Row Level Security (RLS) is enabled
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for public/authenticated read and write
DROP POLICY IF EXISTS "Allow public read access on system_settings" ON public.system_settings;
CREATE POLICY "Allow public read access on system_settings"
    ON public.system_settings FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow public update access on system_settings" ON public.system_settings;
CREATE POLICY "Allow public update access on system_settings"
    ON public.system_settings FOR UPDATE
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public insert access on system_settings" ON public.system_settings;
CREATE POLICY "Allow public insert access on system_settings"
    ON public.system_settings FOR INSERT
    WITH CHECK (true);

-- 4. Seed single default row (id = 1, active_chatbot_model = 'gemini') if not exists
INSERT INTO public.system_settings (id, active_chatbot_model, updated_at, created_at)
SELECT 1, 'gemini', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM public.system_settings WHERE id = 1);

-- In case a row exists but id is different, ensure row with id=1 is present
INSERT INTO public.system_settings (id, active_chatbot_model)
VALUES (1, 'gemini')
ON CONFLICT (id) DO NOTHING;
